# 必填，产品，使用run_xx.py执行用例时，不从这里取数
product: 'ydzj_test'
# 必填，环境，使用run_xx.py执行用例时，不从这里取数
env: 'prod'

# 必填，浏览器
browserName: Chrome
# 必填，后台登录url
login_url:
  test: "https://xxx.com"
  prod: "https://yyy.com."
# 非必填（自定义项），后台url
zj_url:
  test: "https://xxx2.com"
  prod: "https://yyy2.com"

# 非必填（自定义项），默认基础数据
default_basic_data:
  company: 'UI自动化测试公司'
  project: 'UI自动化测试项目'
  phase: '一期'
  bidsec: '测试标段1'
  building: '测试1栋'
  contractor1: '马可波罗'
  contractor2: '中建三局'

# 非必填（自定义项），登录信息
login_info:
  test:  # 测试环境
    corp_id: apitest  # 企业代码
    u_p:  # 用户名:密码
      apitest: [passwd, '超级用户']  # 默认首位为超管账号密码
      ui_js1: [passwd, 'ui建设1']
      ui_jl1: [passwd, 'ui监理1']
  prod:  # 生产环境
    corp_id: apitest
    u_p:
      apitest: [passwd, '超级用户']  # 默认首位为超管账号密码
      ui_js1: [passwd, 'ui建设1']
      ui_jl1: [passwd, 'ui监理1']

# 必填，报告
report_name: '移动质检自动化测试'

# 必填，邮件
email:
  host: "smtp.exmail.qq.com"
  user: "xxx@mingyuanyun.com"
  password: "passwd"
  port: "465"
  to_addr: ["huangyj02@mingyuanyun.com"]
  cc_addr: ["huangyj02@mingyuanyun.com"]
  subject: "移动质检"

# 必填，数据库连接配置
mysql_link:
  test:
    host: "xxx.mysql.rds.aliyuncs.com"
    port: "3306"
    user: "user"
    pwd: "passwd"
    db_name: "mycommunity_apitest"
  prod:
    host: "xxx.rwlb.rds.aliyuncs.com"
    port: "3306"
    user: "user"
    pwd: "passwd"
    db_name: "mycommunity_apitest"

